name: Calling Workflow 2
on:
  push:
    branches:
    - develop

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hello from Calling Workflow 2"
    - run: echo "My ref is " + ${{ github.ref }}

  reusable_workflow:
    uses: ./.github/workflows/called.yml