name: Calling Workflow 1
on:
  push:
    branches:
    - 'release/**'
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hello from calling 1 workflow"
    - run: echo "My ref value is:" + ${{ github.ref }}

  reusable_workflow:
    uses: ./.github/workflows/called