name: e2e Workflow
on:
  push:
    branches:
    - develop
jobs:
  sleep-job:
    runs-on: ubuntu-latest
    steps:
    - name: Pause until all workflows are completed
      uses: willgarcia/workflow-wait-action@0.1.0
      with:
        access_token: ${{ github.token }}
        workflows: |
          Build Workflow
  get-commit-hash:
    runs-on: ubuntu-latest
    needs: sleep-job
    steps:
    - name: Repository Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get Last Successful Commit Hash of Build Workflow
      id: last-successful-commit
      uses: PranavNair0001/last-successful-build-action@v2.1
      with:
        token: ${{ github.token }}
        branch: "develop"
        workflow: "Build Workflow"
        verify: true
    - name: Get Commit Hash of current Workflow Run
      id: current-commit
      run: echo "::set-output name=sha::${GITHUB_SHA}"
    outputs:
      build-hash: ${{ steps.last-successful-commit.outputs.sha }}
      current-hash: ${{ steps.current-commit.outputs.sha }}

  view-hash:
    runs-on: ubuntu-latest
    needs: get-commit-hash
    steps:
    - name: View Last Successful Commit Hash of Build Workflow
      run: echo ${{ needs.get-commit-hash.outputs.build-hash }}
    - name: View Commit Hash of current Workflow Run
      run: echo ${{ needs.get-commit-hash.outputs.current-hash }}
    outputs:
      e2e-hash: ${{ needs.get-commit-hash.outputs.sha }}
      current-hash: ${{ needs.get-commit-hash.outputs.sha }}

  maven-central-deploy-develop:
    needs: view-hash
    if: ${{ (github.ref_name == 'develop') && (needs.view-hash.outputs.e2e-hash == needs.view-hash.outputs.current-hash) }}
    uses: ./.github/workflows/release.yml
